sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Co3cZhlynHF7cte87ceFXLe1VEzeYbok6sUxk8sN0V+ZR86uljWvcZGIOk6nE/TdW3GeBbm4+ny7oq08vhSXUMjPFWRRjuUVkLxJz3w3h6wG43/COPtfnoGIYSP1okGlmjr+467P6Z+F3zaU3M2UmDN45j0vHMoU0/wD9hYZAwEK7U3J5XnX1ZsgMkdhMgp+ftIFTVFT37i5rInlTK2IMNFxUW0HckJXSWY7+JZKZeqVFPYftXS9pX8GA+JBs/lW5hAJATYF/vJXZ6RBgPnWgsdv2DC0u+ccb38/T5zxX1yIdpals129CILz76Xxtx2HOy90SSV3Cr2XUZlEPcBPkNmP6uoIa1yVhC0GzfVf8ZkLdtTqu/76R/+ca0pCtZegoqu63giN5S3ag6ivjBK6AIJPoL9hMLEtWKHy1vhjudfyiwP+0IXhZcJ0yQ3AUt/goxtNzmUhdGvanfuWPX1uzUI1HKjigv8qll7oT4FiYQgPCVgwG3/B0VH/MGrYwTrfuNon9YNkAu58azStLXEkMkFsQd30vW39vYFwP7IXalgUHmHiPtvSEojk9M6nwrF8SAR0V8hGbt7OeXnMwy5OwgA4mPGz+7hwG7vbRWSc3YjDacGTdiButVtEvM3Mkq+hn1h++X+J2jZT98KDDOT+ulUjpNp4qmkqrjO4YICvJEk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Merry-Wives-of-Windsor_2237
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy